version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  build_docker_image:
    executor: docker-executor
    steps:
      - checkout # Pulls the latest code from GitHub
      - run:
          name: Set up Maven and build
          command: |
            # Download dependencies and build the Spring Boot application
            mvn clean install
      
      - run:
          name: Build Docker image
          command: |
            # Build a Docker image from the Dockerfile in your repository
            docker build -t your-dockerhub-username/your-image-name:${CIRCLE_SHA1} .
      
  push_docker_image:
    docker:
      - image: circleci/python:3.7 # This is needed to run the Docker commands
    steps:
      - setup_remote_docker:
          version: 20.10.7 # Ensures Docker is available on the machine
      - run:
          name: Docker login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker image
          command: |
            # Tag the Docker image with the CircleCI SHA for uniqueness
            docker tag your-dockerhub-username/your-image-name:${CIRCLE_SHA1} your-dockerhub-username/your-image-name:latest
            
            # Push the Docker image with both SHA and "latest" tags to Docker Hub
            docker push your-dockerhub-username/your-image-name:${CIRCLE_SHA1}
            docker push your-dockerhub-username/your-image-name:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_docker_image
      - push_docker_image:
          requires:
            - build_docker_image
