version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:17.0.10

jobs:
  build_push_docker_image:
    executor: docker-executor
    steps:
      - checkout # Pulls the latest code from GitHub
      - run:
          name: Set up Maven and build
          command: |
            # Download dependencies and build the Spring Boot application
            mvn clean install
  
      - setup_remote_docker:
          version: docker23 # Specify the Docker version you want to use
          docker_layer_caching: true # Optional: speeds up Docker builds      
      
      - run:
          name: Build Docker image
          command: |
            # Build a Docker image from the Dockerfile in your repository
            docker build -t ahmedali432/springboot:${CIRCLE_SHA1} .
      - run:
          name: List Docker images
          command: docker images
      - run:
          name: Tag Docker image
          command: |
            docker tag ahmedali432/springboot:${CIRCLE_SHA1} ahmedali432/springboot:latest          
      - run:
          name: Docker login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker image
          command: |            
            # Push the Docker image with both SHA and "latest" tags to Docker Hub
            docker push ahmedali432/springboot:${CIRCLE_SHA1}
            docker push ahmedali432/springboot:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_docker_image
      - push_docker_image:
          requires:
            - build_docker_image
          filters:
            branches:
              only: master   
